Repository Mercateo/factcast, pull requests merged in 2019-04, with the labels that each got.

#308 Fix catchup with startingFrom-FactId
  factcast-core/src/main/java/org/factcast/core/util/FactCastJson.java
  factcast-core/src/test/java/org/factcast/core/util/FactCastJsonTest.java
  factcast-store-inmem/src/main/java/org/factcast/store/inmem/InMemFact.java
  factcast-store-inmem/src/main/java/org/factcast/store/inmem/InMemFactStore.java
  factcast-store-inmem/src/test/java/org/factcast/store/inmem/AfterPredicateTest.java
  factcast-store-inmem/src/test/java/org/factcast/store/inmem/InMemFactTest.java
  factcast-store-test/src/main/java/org/factcast/store/test/AbstractFactStoreTest.java
Labels: help wanted

#333 Issue329 PgTokenStore
  factcast-core/src/main/java/org/factcast/core/util/FactCastJson.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgConstants.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgFactStoreInternalConfiguration.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/PgTokenStore.java
  factcast-store-pgsql/src/main/resources/db/changelog/db.changelog-master.yaml
  factcast-store-pgsql/src/main/resources/db/changelog/factcast/issue329/createTokenStore.sql
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/PgTokenStoreTest.java
  factcast-store-pgsql/src/test/resources/test_schema.sql
Labels: help wanted

#368 Spotless polish
  pom.xml
  src/eclipse/config/eclipse.importorder
  src/eclipse/config/eclipse_code_formatter.xml
  src/eclipse/config/eclipse_javascript_formatter.xml
Labels: maintenance

#378 #55-basicauth: added basicauth
  .bettercodehub.yml
  factcast-client-grpc-boot1/src/main/java/org/factcast/client/grpc/boot1/BackwardsCompatibleConfiguration.java
  factcast-client-grpc/src/main/java/org/factcast/client/grpc/GrpcFactStore.java
  factcast-client-grpc/src/main/java/org/factcast/client/grpc/Lz4GrpcClientCodec.java
  factcast-client-grpc/src/test/java/org/factcast/client/grpc/ClientStreamObserverTest.java
  factcast-client-grpc/src/test/java/org/factcast/client/grpc/GrpcFactStoreTest.java
  factcast-core/src/main/java/org/factcast/core/DefaultFactCast.java
  factcast-core/src/main/java/org/factcast/core/FactValidation.java
  factcast-core/src/main/java/org/factcast/core/store/AbstractFactStore.java
  factcast-core/src/main/java/org/factcast/core/util/FactCastJson.java
  factcast-core/src/test/java/org/factcast/core/DefaultFactCastTest.java
  factcast-core/src/test/java/org/factcast/core/NullFact.java
  factcast-core/src/test/java/org/factcast/core/util/FactCastJsonTest.java
  factcast-examples/factcast-example-client-basicauth/.no-owasp
  factcast-examples/factcast-example-client-basicauth/README.md
  factcast-examples/factcast-example-client-basicauth/pom.xml
  factcast-examples/factcast-example-client-basicauth/src/main/java/org/factcast/example/client/basicauth/ExampleClient.java
  factcast-examples/factcast-example-client-basicauth/src/main/java/org/factcast/example/client/basicauth/HelloWorldRunner.java
  factcast-examples/factcast-example-client-basicauth/src/main/resources/application.properties
  factcast-examples/factcast-example-client-basicauth/src/test/resources/application.properties
  factcast-examples/factcast-example-server-basicauth/.gitignore
  factcast-examples/factcast-example-server-basicauth/.no-owasp
  factcast-examples/factcast-example-server-basicauth/pom.xml
  factcast-examples/factcast-example-server-basicauth/src/main/docker/Dockerfile
  factcast-examples/factcast-example-server-basicauth/src/main/java/org/factcast/example/server/ExampleServerWithPostgresContainer.java
  factcast-examples/factcast-example-server-basicauth/src/main/resources/application.properties
  factcast-examples/factcast-example-server-basicauth/src/main/resources/banner.txt
  factcast-examples/factcast-example-server-basicauth/src/main/resources/factcast-security.json
  factcast-examples/factcast-example-server-basicauth/src/main/resources/logback.xml
  factcast-grpc-api/src/main/java/org/factcast/grpc/api/CompressionCodecs.java
  factcast-server-grpc/pom.xml
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactCastGrpcServerConfiguration.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactCastSecurityConfiguration.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/FactStoreGrpcService.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/GrpcCompressionInterceptor.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/Lz4GrpcServerCodec.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/auth/AccessCredential.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/auth/CredentialConfiguration.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/auth/FactCastRole.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/auth/FullAccessCredential.java
  factcast-server-grpc/src/main/java/org/factcast/server/grpc/auth/ReadOnlyAccessCredential.java
  factcast-server-grpc/src/test/java/org/factcast/server/grpc/FactStoreGrpcServiceTest.java
  factcast-server-grpc/src/test/java/org/factcast/server/grpc/auth/CredentialConfigurationImplTest.java
  factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/client/grpc/GrpcFactStoreAutoConfiguration.java
  factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/client/grpc/LZ4ClientAutoConfiguration.java
  factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/server/grpc/FactCastGrpcServerAutoConfiguration.java
  factcast-spring-boot-autoconfigure/src/main/java/org/factcast/spring/boot/autoconfigure/server/grpc/LZ4ServerAutoConfiguration.java
  factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/listen/PgConnectionSupplier.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/PgFactStoreTest.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/PgSqlListenerTest.java
  factcast-store-pgsql/src/test/java/org/factcast/store/pgsql/internal/listen/PgConnectionSupplierTest.java
  factcast-store-test/src/main/java/org/factcast/store/test/AbstractFactStoreTest.java
  pom.xml
Labels: GRPC, doc, easy, help wanted
